name: Scrap todays games prices

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *

jobs:
  downloadStatus:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm start
        env:
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - run: |
          git config user.name AlejandroGutierrezB
          git config user.email alejandrogutbarce@gmail.com
          git add .
          git commit -m "Add prices for today"
          git push --set-upstream origin master
          git push
